@extends("theme")
@section("contents")
<div class="container">
<h1><BR><b><i>MUMMY</i></b></h1>
            <br>
            
            <div class="row">
                <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                <img src="https://i.pinimg.com/originals/32/76/d1/3276d1b360f55d895ac22d4304935532.jpg" class="img-fluid" alt="...">
                <h3><br><b>Ancient Egypt</b></h3>
                <p class="fst-italic"><br>In the ancient Egyptian city of Thebes, in the year 1290 B.C, Seti I rules as pharaoh. Residing in Thebes is also the High Priest of Osiris, Imhotep, who acts as advisor, counsel and friend to Seti, but who houses a secret: Imhotep harbours a secret love, Anck-Su-Namun, Seti's mistress. The two love one another more than life itself, but as long as Seti lives, they may never be together, leaving them with the plan of assassinating the pharaoh.<br><br>As a precaution to ensure that Anck-Su-Namun stayed within Seti's rule, she is painted in several coats of golden body paint, which ensures that no other man might touch her, though the precaution is thrown out when Anck-Su-Namun comes close to Imhotep as the two are in Anck-Su-Namun's residence and the they share a kiss, which ends in Imhotep smearing the paint on Anck-Su-Namun's left arm. At that moment, Seti, who has just come to Anck-Su-Namun's residence, is surprised to see Imhotep's priests at the residence, but is utterly infuriated when he sees Anck-Su-Namun with the paint on her arm smeared and Seti asks which man dared to touch her. At that moment, Imhotep comes from behind the pharaoh and is about to assassinate Seti with a dagger, but ceases as Anck-Su-Namun stabs Seti with another dagger, her lover joining in until Seti is killed.<br><br>The Medjai, the pharaoh's elite guard, storm the residence, seeking whoever had committed the crime. The Medjai were too late to catch one of the real culprits as Imhotep leaves the scene at the request of Anck-Su-Namun, who states that only he could bring her back to life were something to happen. Upon discovering Seti's corpse and Anck-Su-Namun with a dagger, the guards watch as Anck-Su-Namun, feigning treachery, stabs herself in the stomach with the dagger used to murder Seti.

                    Soon after Anck-Su-Namun's burial, Imhotep and his priests unearth her body and race into the deserts to seek Hamunaptra, the City of the Dead, where the wealth of kings and the resting place for pharaohs lays. Here Imhotep seekes out the black Book of the Dead so as to revive his love, and begins to perform the spell that would bring her to life. But before the ritual can be completed, the Medjai, who had followed the priests as they headed to Hamanaptra, storm the chamber where the ritual is being performed. To commit an act such as bringing one back from the dead is blasphemy of the worst calibre, and so the priests are all condemned to death by being mummified while they were alive.<br><br>Imhotep, having led them into their sin, is condemned to endure the Hom-Dai, a curse so horrible that it had never before been bestowed. The priest's tongue is ritualistically cut out, and he is bound tight in wrappings, placed in a sarcophagus which is filled with flesh-eating scarab beetles. As the scarabs slowly eat Imhotep alive, the lid is placed over the sarcophagus and sealed with a key resembling a puzzle-box. The Medjai and their descendants vow from that time on to watch over the city's ruins so that none might find either Imhotep or the means to bring him back to life, for if he should be revived, all mankind would be doomed.</p>
                </div>
            </div>
            <br>
            <h3><b>Battle at Hamunaptra</b></h3>
            <div class="row">
                <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                <p class="fst-italic"><br>In 1923 A.D, years after the pharaohs of Egypt had fallen, the Medjai still exist, becoming a furtive secret society over the years with the same goal as they did centuries ago: to ensure that none finds the buried Imhotep. One group of Medjai led by Ardeth Bay stand vigil over Hamunaptra, witnessing a garrison of the French Foreign Legion that have found the ruins, setting up their post within the crumbling walls. The Legionnaires in the garrison believed so much that Hamunaptra existed that they trekked across Libya into Egypt, and encountering a great army of Tuareg warriors at the site. Rick O'Connell, an American serving as corporal in the Legion, has been promoted once the leader of the garrison, Colonel Guizot, deserts the ruins on horseback, leaving his men on their own. O'Connell leads his fellow Legionnaires into successfully bringing down many Tuaregs, but as the battle wages on, the Tuaregs kill off more and more Legionnaires until only O'Connell himself and another Legionnaire, a man named Beni Gabor, survive. O'Connell blasts away many Tuaregs with his pistols, but finds himself outnumbered once his bullets run out. The Tuaregs chase him into a corner, but can't fire, as their horses are frightened off by something within the sand; with this, the Tuaregs leave Hamunaptra, leaving O'Connell alone to face whatever is in the sand, until the movements in the sand drive him off as well. Running off into the desert, O'Connell notices a group of men on horseback watching him in the distance, Medjai, who decide not to kill him, as the desert would do that.</p>
                </div>
            </div>
            <br>
            <h3><b>Desert Journey</b></h3>
            <div class="row">
                <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                <p class="fst-italic"><br>The four riders travel through the desert to find Hamunaptra, until they reach a point in the Sahara where they encounter Beni and his employers, now with three dozen diggers in their midst. Both groups pause for a moment as the sun rises, then resume their journey, each group racing against the other to reach the city first. The group consisting of Evelyn, O'Connell, Jonathan, and the Warden win the race, reaching the ruins before the others do. Once camp is being set up, the Americans take the best areas to search for treasures to themselves, as the smaller group searches for openings to the chambers below.</p>
                </div>
            </div>
            <br>
            <h3><b>Underground Chambers</b></h3>
            <div class="row">
                <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                <p class="fst-italic"><br>Making their way to the underground chambers, the group headed by O'Connell searches through the tunnels for any areas in which to dig and find treasures. Reaching the base of the statue of Anubis, the four treasure hunters begin to hear strange sounds coming from around the statue; guns out in the open, they turn around to face the source of the sounds, coming instead face-to-face with the rival group, also armed. With both groups meeting in the same area, the argument over the right to dig at the statue base begins, ending with the Americans and their diggers winning the statue base; as Evelyn notices quietly that there is another chamber below, she surrenders the chamber to the larger group.

                    Beginning to dig and pry at the stone ceilings, O'Connell, Evelyn and Jonathan believe that they can find the secret compartment that houses the Book of Amun-Ra, and take it while the Americans are all distracted. As they are working on the ceilings, the Warden separates himself from the rest of the group, making his way through a passageway where he finds an elaborate mural on the wall. On the mural are several shiny stones, which the Warden identifies as precious and begins to pry off the walls with a knife.<br><br>Meanwhile, in the chamber above, one of the Americans, a man named Henderson is about to pry open the compartment at the statue base of Anubis in the hopes of finding treasure before he is stopped by the Egyptologist Dr. Allen Chamberlain, who informs him that that the Pharaoh was no fool to make his valuables so easily obtained, and so advises the treasure seekers to have the diggers open the compartment instead. Three diggers step forward and began to pry at the compartment as the Egyptologist urges them on, pushing harder and harder until a torrent of salt acid shoots out at the three diggers, killing them<br><br>After some time has passed, Jonathan manages, by accident, to find a compartment where a sarcophagus is stored, releasing a large stone coffin. While the two others present stand in awe at this find, the Warden is still prying stones off the walls elsewhere, until one stone, having missed his bag and fallen onto the floor, cracks open, revealing a living scarab beetle, that tears open the Warden's shoe and eats its way up the Warden's skin to his head.

                    The other three examine the sarcophagus that has fallen from the ceiling, and deduce that the puzzle box that had been the cause of the Medjai attack on the riverboat is the key to opening the sarcophagus. Putting the key's ends in place, the three treasure seekers understand how to open the sarcophagus, but the moment is cut short when screaming erupts from the tunnels outside. Guns out again, O'Connell and the Carnahans rush out to find the Warden screaming and clawing at his head, running almost as if mad; pushing the others out of the way, the Warden runs shrieking head first into a stone wall, killing himself.</p>
                </div>
            </div>
            <br>
            <h3><b>Escape from Hamunaptra</b></h3>
            <div class="row">
                <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                <p class="fst-italic"><br>In another corridor, Beni is walking with a saddlebag full of stolen valuables from the treasuries, triggering the collapse of Hamunaptra by leaning the bag on a lever on the wall. O'Connell, Jonathan and Evelyn, hear the walls crumbling, take the opportunity to leave, though Jonathan has tripped on a staircase and drops the Book of Amun-Ra in a moat; Evelyn chastises Jonathan for dropping the Book before O'Connell and Jonathan hurry her along.<br><br>As the three ran through the corridors and chambers, Jonathan stops in the treasury, wondering why they can't take some of the treasures with them before O'Connell and Evelyn rush him out as well. As they are escaping the crumbling ruins, a familiar face follows them: Beni, who had tried to catch up with O'Connell, but could not make it through a collapsing doorway in time. O'Connell, despite Beni's previous betrayals, makes an effort to help Beni out of the chamber, but could not pull him out in time as the doorways closes, sealing Beni in, a carnivorous scarab appears atop a statue's head and hisses menacingly at Beni, who tries to stave the bug off with his torch. With this, swarms of the scarabs came out to greet a horrified Beni. He tries to stave them off as well, only succeeding in causing more to emerge. Beni stands in the treasury trembling and whimpering with terror as his torch quickly dies out, leaving Beni to be devoured alive in the pitch black darkness. O'Connell, Evelyn and Jonathan run quickly from the ruins, reaching the surface as it crashes down in a massive series of dusty explosions.<br><br>Once the trio have escaped, a hand reached out to Jonathan: Ardeth has escaped the ruins alive, astride a camel, and informs them that they have earned the respect of the Medjai for their defeat of Imhotep. Blessing them in Allah's name, Ardeth rides off into the sunset, leaving them behind as Jonathan complains that they go home empty-handed, but O'Connell says that he, at least, is not empty-handed, as he has found Evelyn, kissing her deeply, this sight displeasing Jonathan who attempts to kiss a camel. The three survivors then mount camels and ride off into the sunset, unaware that they have some treasures with them in a saddlebag, courtesy of Beni.</p>
                </div>
            </div>
      </div>
@endsection