@extends("theme")
@section("contents")
<div class="container">
          <h1><BR><b><i>PACIFIC RIM</i></b></h1>
            <br>
            <h3><b>A Prehistoric Scouting Mission</b></h3>
            <div class="row">
                <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                <img src="https://static1.srcdn.com/wordpress/wp-content/uploads/2017/10/Pacific-Rim-Uprising-Giant-Kaiju.jpg?q=50&fit=crop&w=740&h=370&dpr=1.5" class="img-fluid" alt="...">
                <p class="fst-italic"><br>A mysterious race of interdimensional colonists known as the Precursors move from world to world, consuming everything they leave in their wake. The Precursor masters grow clone monsters to send through from their world, the Antiverse, through a breach to quell the local population to make way for colonization. After taking over, they drain the world of its resources, and then move on. During the triassic period, the masters attempted to populate the Earth by opening a the breach and sending the very first wave of kaiju, the creatures we now know of as dinosaurs. The dinosaurs were powerful monsters, but the Earth's atmosphere was not hospitable and they weren't able to survive. Eventually, this first wave died off, and the breach was closed</p>
                </div>
            </div>
            <br>
            <h3><b>2013 - The Second Invasion</b></h3>
            <div class="row">
                <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                <img src="https://static2.srcdn.com/wordpress/wp-content/uploads/2018/03/Pacific-Rim-Jaegers-March-Over-Ocean.jpg?q=50&fit=crop&w=740&h=370&dpr=1.5" class="img-fluid" alt="...">
                <p class="fst-italic"><br>On August 10th, 2013, the breach was again opened. Recent human activity had significantly altered the Earth's atmosphere, terraforming it to an extent that made another takeover attempt viable. It all started when San Francisco experienced a massive Earthquake, followed by the first massive kaiju, the "Trespasser." The Trespasser was virtually uninhibited in its destruction, demolishing the Golden Gate Bridge, flattening buildings, and killing tens of thousands before it's finally put down by three nuclear missiles.<br><br>In the ensuing months, similar attacks would happen around the world, humanity finding itself woefully ill-equipped to combat this new threat. In September of 2014, just over a year after the first kaiju encounter, the Pan Pacific Defense Corps is formed and its member nations begin construction of Jaegers - giant mechanical war machines designed to go toe to toe with the Kaiju. The project is overseen by Stacker Pentecost, who volunteers to be the first test subject for the "pons" system, the neural bridge that allows humans to control the Jaegers.<br><br>Due to the size of the neural load, one human is not sufficient to pilot the massive machines, so two humans with a balanced mental connection must pilot together, using the pons and "the drift" to link their consciousness and fight as a singular entity. Eventually, another kaiju attack occurs, and a Jaeger is successfully deployed to combat it. The Mark-1 Jaeger is successful, signaling a major victory for the program as many more countries begin developing their own Jaegers and the Pan Pacific Defense Force sees an influx of pilots of jaeger training.</p>
                </div>
            </div>
            <br>
            <h3><b>2016 - Yancy And Raleigh Beckett Become Jaeger Pilots</b></h3>
            <div class="row">
                <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                <img src="https://static3.srcdn.com/wordpress/wp-content/uploads/2018/03/Pacific-Rim-Gipsy-Danger-Falls.jpg?q=50&fit=crop&w=740&h=370&dpr=1.5" class="img-fluid" alt="...">
                <p class="fst-italic"><br>Yancy and Raleigh Becket, two American brothers from Anchorage, Alaska, enlist in the Jaeger Academy. As brothers, they have a natural bond perfectly suited for the drift. When Beckett brothers graduate in 2017, they are assigned to the Anchorage Shatterdome and given command of the mark-3 Jaeger "Gypsy Danger" and tasked with the defense of the Alaskan coastline under the command of Stacker Pentecost. Over the next 3 years, the Beckett brothers pilot Gypsy Danger against 4 kaiju, killing all of them. During their encounter with a 5th kaiju, Gypsy danger is severely damaged and Yancy is killed, but Raleigh is able to mentally wrestle control and solo pilot the failing Jaeger to victory one more time. After the battle, Raleigh exits the Jaeger program and Gypsy Danger is sent to Oblivion Bay, a Jaeger graveyard near Oakland, California.<br><br>Over the next 5 years, the Jaeger program begins to lose favor with the UN, who begins cutting funds to the program as the Pan Pacific Defense Corps begins building a massive wall instead of continuing to build Jaegers. Not willing to give up on the Jaeger program, Stacker Pentecost attempts to round up as many of the mechs as he can, recovering Gypsy Danger at the Anchorage Shatterdome for reconstruction before moving his operations to Hong Kong - the last remaining Jaeger program holdout - in 2024. Pentecost's son, Jake, was also a part of the Pan Pacific Defense force, but when Stacker's attention started to focus more on his adopted daughter, Mako Mori, Jake has a falling out with his father and leaves the Jaeger program.</p>
                <img src="https://static0.srcdn.com/wordpress/wp-content/uploads/2018/03/Pacific-Rim-Raleigh-Mako.jpg?q=50&fit=crop&w=740&h=370&dpr=1.5" class="img-fluid" alt="...">
                </div>
            </div>
            <br>
            <h3><b>2025 - The Battle Of The Breach</b></h3>
            <div class="row">
                <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                <p class="fst-italic"><br>With the frequency of attacks increasing, the Jaeger program quickly dying, and the Pan Pacific Defense Force obsessed with building walls that he kaiju destroy with ease, Stacker Pentecost hatches a plan to lay siege on the breach itself. He brings Raleigh Beckett out of retirement, discovering (to his dismay) that he's drift compatible with his adopted daughter, Mako, and the two are assigned to the renovated and improved Gypsy Danger.<br><br>In an effort to learn more about the kaiju, scientist Newton Geiszler initiates a drift with a kaiju brain, learning a number of the monster's secrets and motivations, but the breach is a two-way connection, so the kaiju's masters also learn about humanity's plans to assault the breach. Geizler's kaiju drift is followed by the first ever double event as two kaiju emerge from the breach. 3 Jaegers, Crimson Typhoon, Cherno Alpha, and Striker Eureka are deployed to stop them, but the kaiju prove too strong. Crimson Typhoon and Cherno Alpha are quickly destroyed and Striker Eureka, the only mark-5 Jaeger in existence, engages the kaiju, only to be taken out of commission by a surprise EMP blast from one of the kaiju.<br><br>As an older model, Gypsy Danger is an analog Jaeger, making it impervious to the EMP. Despite a lack of adequate drift training between its pilots, Gypsy Danger is deployed to protect Hong Kong. While the city doesn't make it by unscathed, Gypsy Danger is able to single-handedly defeat both kaiju.<br><br>With a triple threat imminent, Pentecost fast tracks the attack on the breach. One of Striker Eureka's pilots, Hercules Hanson, was injured during the double event in Hong Kong, so Pentecost partners with Chuck Hansen instead. Over the years, Pentecost has mastered the ability to not allow his memories to bleed into the drift, allowing him to successfully pair with nearly anyone.<br><br>As they approach the drift, a triple even occurs, including a category 5 kaiju, the largest ever seen. In a sacrificial play, Pentecost and Hanson detonate Striker Eureka to take out one of the kaiju, while Mako and Raleigh defeat the category 5 monster before sending Gypsy Danger into the breach, reactor set to self-destruct, finally closing the door on the kaiju.</p>
                </div>
            </div>
            <br>
            <h3><b>2035 - The Assault On Mount Fuju</b></h3>
            <div class="row">
                <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                <img src="https://static1.srcdn.com/wordpress/wp-content/uploads/2018/03/Pacific-Rim-Uprising-Movie-Review.jpg?q=50&fit=crop&w=740&h=370&dpr=1.5" class="img-fluid" alt="...">
                <p class="fst-italic"><br>The world enjoys a decade of recovery after the closing of the breach. There were no more attacks, but so much infrastructure had been damaged by the kaiju that resources are scarce and food is the most valuable commodity.<br><br>Living in a half-destroyed mansion, Jake Pentecost has taken to scavenging old Jaeger parts from decommissioned Jaegers. Jaegers are still around. In fact there are more of them, as the advanced technology left over from the development of Jaegers has even enabled some people to build mini Jeagers, but they are no longer used for combat, since there are no Kaiju to fight. Instead, they are mostly kept around for ceremonial purposes. Even though, the Hong Kong Shatterdome still has a training program, and Jake re-enlists as a Jaeger pilot.<br><br>The concept of remotely controlled Jaeger's are a taboo, but Shao Industries is working to develop them anyway. When it's ready for a public demonstration, a rogue Jaeger attacks and kills Mako Mori. The rogue Jaeger is controlled by a Kaiju brain developed in secret by Shao Industries, under the guidance of  Dr. Newton Geiszler. The connection he'd made to the precursors before the Battle of the Breech had more of an influence than anyone knew, and he was under their control.<br><br>Geiszler had developed special drones that can turn a Jaeger into a Kaiju hybrid. After taking over a number of Jaegers, they re-open breaches to allow several Kaiju back through. The Kaiju want to destroy themselves in Mount Fuji, where their volatile blood will start a chain reaction and terraform the earth, killing everyone and making it more habitable for their takeover.

<br><br>The Jaegers defeat several Jaegers, but Dr. Geiszler unleashes a new development that brings together several injured kaiju into a massive beast that makes its way toward Mount Fuji with all the Jagers but Pentecost's Gypsey Avenger out of commission. Gypsey Avenger is sent on a last-ditch effort to kill the kaiji, launching into it with a giant rocket, finally halting its progress and saving the day.<br><br>Sick of the kaiju coming through to terrorize the Earth, Jake Pentecost decides to end the struggle with the precursors once and for all, declaring his intent to go into the breach to take them on in the Antiverse.</p>
                </div>
            </div>
            <br>
            <h3><b>Pacific Rim: The Black</b></h3>
            <div class="row">
                <div class="col col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
                <img src="https://static1.srcdn.com/wordpress/wp-content/uploads/2021/02/Jaeger-from-Pacific-Rim-The-Black-anime.jpg?q=50&fit=crop&w=740&h=370&dpr=1.5" class="img-fluid" alt="...">
                <p class="fst-italic"><br>Pacific Rim: The Black is an all-new animated series set in the same universe as the two Pacific Rim live-action films. The Black is not a sequel or a prequel and takes place in Australia. It follows two siblings, Hayley and Taylor, who use a recovered Jaeger called the Atlas Destroyer to search for their parents. The animated series, a continuation of the original movies, is set years after the events of Pacific Rim and its live-action sequel. By this point in time, people have stopped using Jaegers for a very long time, with Hayley and Taylor using one five years after the kaiju have taken over Australia, forcing a mass evacuation. The series explores a world where kaiju are everywhere and what human survival looks like now.</p>
                </div>
            </div>
      </div>
@endsection